import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import buildClient from '@/api/build-client';
import {headers} from 'next/headers'
import AuthProvider from '@/_lib/session-context'
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const incommingHeader=await headers()
      const header=Object.fromEntries(incommingHeader)
      const {data}=await buildClient(header).get('/api/users/currentuser')//currentuser for urlcurrentUser for object returned
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        <AuthProvider user={data}>
        
        {children}
        </AuthProvider>
      </body>
    </html>
  );
}
